# Generated by Django 3.1.7 on 2021-05-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_publicaciones_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='name_user',
            field=models.CharField(default='', max_length=140),
        ),
    ]
